### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by skinkie** [zeromq/zwssock#8]
I am reviewing the example. Shouldn't there be a `zmsg_destroy(&msg);` after line 55?

https://github.com/zeromq/zwssock/blob/master/src/CZMQ-ZWSSock/main.c#L55

**Comment by bluca** [comment]
the send function will destroy the message on successful send - perhaps the example could be updated to take action on error, would you send a PR to implement this?

**Comment by skinkie** [comment]
Which will always be the case at this moment ;) do you want me to change this as well?

```c
int zwssock_send(zwssock_t *self, zmsg_t **msg_p)
{
    assert(self);
    assert(zmsg_size(*msg_p) > 0);
    zmsg_send(msg_p, self->data);
    return 0;
}
```

**Comment by bluca** [comment]
sounds good

**Comment by skinkie** [comment]
@bluca can you give me the exact line in the libzmq that does what you say with respect to destroying the message after a succesful send?

**Comment by somdoron** [comment]
https://github.com/zeromq/czmq/blob/master/src/zmsg.c#L150

**Comment by skinkie** [comment]
That explains :-) Was looking in the wrong library.
